# Generated by Django 4.1.3 on 2023-08-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feetfirstapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(max_length=30),
        ),
    ]
