# Generated by Django 4.1.3 on 2023-08-02 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feetfirstapi', '0002_alter_order_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feetfirstapi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feetfirstapi.user')),
            ],
        ),
    ]
