# Generated by Django 4.2.1 on 2023-08-09 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feetfirstapi', '0003_favoriteproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_completed',
            new_name='open',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
    ]
