# Generated by Django 4.2.1 on 2023-08-09 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feetfirstapi', '0005_alter_order_date_placed_alter_order_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
